api_platform:
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        jsonhal: [ 'application/hal+json' ]

    #enable_docs: false
    #enable_entrypoint: false
    #enable_swagger: false
    #enable_swagger_ui: false"
